package io.datcord.entity.feature;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;
import lombok.ToString;


/**
 * This entity represents a feature in the system.
 * It has an autogenerated ID as primary key.
 */

@Entity
@ToString
@Data
public class Feature {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int id;
}
